services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - wordpress-network

  db:
    image: mysql:5.7.28
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$DB_ROOT_PASSWORD"]
      timeout: 30s
      retries: 5  
   

  phpadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306  
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    build: 
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./src:/var/www/html:rw
    networks:
      - wordpress-network

volumes:
  db-data: 

networks:
  wordpress-network:
    driver: bridge

  